"""Memory Core -> Obsidian export.

One markdown file per scope, in a dedicated folder (default ``AI Memory/``).

The mirror is a **view**, not a replica that can be edited back:

* it is regenerated wholesale from SQLite, deterministically;
* every block carries the memory id and its provenance in machine-readable
  markers;
* it holds **no independent state** - deleting the folder loses nothing;
* it is excluded from import by default, so ``export`` cannot feed ``import``.

If you want to change a memory, change the note it came from and re-import, or
use the CLI. Editing the mirror is pointless by design: the next export
overwrites it.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Sequence, Tuple

from memory_bridge.config import BridgeConfig
from memory_bridge.obsidian.provenance import BRIDGE_VERSION, ORIGIN

README_NAME = "_README.md"

#: Marks a file as ours, so pruning never touches a human's notes.
GENERATOR_MARKER = "generator: memory-core-bridge"

_SLUG_RE = re.compile(r"[^A-Za-z0-9._\-\u4e00-\u9fff]+")

_README = """# AI Memory

This folder is generated by **Memory Core Bridge {version}** from
`memory.sqlite`. It is a **read-only mirror** of the AI's long-term memory.

- The source of truth is the SQLite database, not these files.
- **Edits here are not remembered.** The next export overwrites the whole file.
- To change a memory, edit the note it came from and re-import, or use the
  `memory-core` CLI.

Nothing is lost if you delete this folder: it is regenerated from the database.
"""


def _utc_now():
    # type: () -> str
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


def scope_slug(scope):
    # type: (str) -> str
    """``project:persona-edgeaiot`` -> ``project-persona-edgeaiot``."""
    return _SLUG_RE.sub("-", str(scope)).strip("-") or "scope"


def _json(value):
    # type: (Any) -> str
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


@dataclass(frozen=True)
class ExportReport(object):
    """What one export wrote."""

    out_dir: str
    exported_at: str
    files: Tuple[str, ...] = ()
    scopes: Tuple[str, ...] = ()
    memory_count: int = 0
    preference_count: int = 0
    project_state_count: int = 0
    pruned: Tuple[str, ...] = ()

    def as_dict(self):
        # type: () -> Dict[str, Any]
        return {
            "out_dir": self.out_dir,
            "exported_at": self.exported_at,
            "files": list(self.files),
            "scopes": list(self.scopes),
            "memory_count": self.memory_count,
            "preference_count": self.preference_count,
            "project_state_count": self.project_state_count,
            "pruned": list(self.pruned),
        }

    def render(self):
        # type: () -> str
        lines = ["Memory Core -> Obsidian export", "=" * 78]
        lines.append("vault export dir : {0}".format(self.out_dir))
        lines.append("exported_at      : {0}".format(self.exported_at))
        lines.append("scopes           : {0}".format(", ".join(self.scopes) or "(none)"))
        lines.append(
            "rows             : {0} memories, {1} preferences, {2} project states".format(
                self.memory_count, self.preference_count, self.project_state_count
            )
        )
        lines.append("")
        for path in self.files:
            lines.append("  wrote  {0}".format(os.path.basename(path)))
        for path in self.pruned:
            lines.append("  pruned {0}".format(os.path.basename(path)))
        return "\n".join(lines)


class ObsidianExporter(object):
    """Writes the markdown mirror."""

    #: Read every row; export is a batch operation, not a hot path.
    ROW_LIMIT = 1000000

    def __init__(self, core, config, now=None):
        # type: (Any, BridgeConfig, Any) -> None
        self.core = core
        self.config = config
        self._now = now

    def _timestamp(self):
        # type: () -> str
        return self._now() if callable(self._now) else _utc_now()

    def export(self, out_dir=None):
        # type: (Optional[str]) -> ExportReport
        target = out_dir or self.config.export_path()
        os.makedirs(target, exist_ok=True)
        exported_at = self._timestamp()

        scopes = self.core.list_scopes()
        files = []
        written_names = set()
        memories_total = 0
        preferences_total = 0
        states_total = 0

        for scope in scopes:
            memories = self.core.list_memories(
                scopes=(scope,), statuses=("active",), limit=self.ROW_LIMIT
            )
            preferences = self.core.list_preferences(scopes=(scope,))
            states = self.core.list_project_states(scopes=(scope,))
            if not (memories or preferences or states):
                continue
            memories_total += len(memories)
            preferences_total += len(preferences)
            states_total += len(states)

            name = "{0}.md".format(scope_slug(scope))
            path = os.path.join(target, name)
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(
                    self._render_scope(
                        scope, memories, preferences, states, exported_at
                    )
                )
            files.append(path)
            written_names.add(name.lower())

        readme_path = os.path.join(target, README_NAME)
        with open(readme_path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(_README.format(version=BRIDGE_VERSION))
        files.append(readme_path)

        pruned = self._prune(target, written_names)
        return ExportReport(
            out_dir=target,
            exported_at=exported_at,
            files=tuple(files),
            scopes=tuple(scopes),
            memory_count=memories_total,
            preference_count=preferences_total,
            project_state_count=states_total,
            pruned=tuple(pruned),
        )

    # -- rendering -----------------------------------------------------

    def _render_scope(self, scope, memories, preferences, states, exported_at):
        # type: (str, Sequence[Any], Sequence[Any], Sequence[Any], str) -> str
        lines = [
            "---",
            "generated: true",
            "{0} {1}".format(GENERATOR_MARKER, BRIDGE_VERSION),
            "source: memory.sqlite",
            "scope: {0}".format(scope),
            "exported_at: {0}".format(exported_at),
            "memory_count: {0}".format(len(memories)),
            "preference_count: {0}".format(len(preferences)),
            "project_state_count: {0}".format(len(states)),
            "---",
            "",
            "> [!warning] 自动生成的镜像",
            "> 本文件由 Memory Core 生成。**在这里的编辑不会被记住**，下次导出会被覆盖。",
            "> 要修改记忆，请编辑它的来源笔记并重新导入，或使用 `memory-core` CLI。",
            "",
        ]
        for memory in sorted(memories, key=lambda item: item.id):
            lines.extend(self._render_memory(memory))
        for preference in sorted(preferences, key=lambda item: (item.key, item.id)):
            lines.extend(self._render_preference(preference))
        for state in sorted(states, key=lambda item: (item.project_id, item.id)):
            lines.extend(self._render_project_state(state))
        return "\n".join(lines).rstrip("\n") + "\n"

    @staticmethod
    def _provenance_bits(record):
        # type: (Any) -> List[str]
        source = getattr(record, "source", None) or {}
        bits = []
        if source.get("origin"):
            bits.append("origin={0}".format(source["origin"]))
        if source.get("external_ref"):
            bits.append("source_ref={0}".format(source["external_ref"]))
        if source.get("event_ids"):
            bits.append("events={0}".format(",".join(source["event_ids"])))
        if source.get("content_hash"):
            bits.append("content_hash={0}".format(source["content_hash"]))
        return bits

    def _render_memory(self, memory):
        # type: (Any) -> List[str]
        header = [
            "id={0}".format(memory.id),
            "kind={0}".format(memory.kind),
            "confidence={0}".format(memory.confidence),
            "salience={0}".format(memory.salience),
            "created={0}".format(memory.created_at),
            "scope={0}".format(memory.scope),
        ]
        if memory.generated_by:
            header.append("generated_by={0}".format(memory.generated_by))
        header.extend(self._provenance_bits(memory))
        lines = ["<!-- memory {0} -->".format(" ".join(header))]
        lines.append(memory.content)
        if memory.tags:
            lines.append("")
            lines.append("tags: {0}".format(", ".join(memory.tags)))
        lines.append("<!-- /memory -->")
        lines.append("")
        return lines

    def _render_preference(self, preference):
        # type: (Any) -> List[str]
        header = [
            "id={0}".format(preference.id),
            "key={0}".format(preference.key),
            "confidence={0}".format(preference.confidence),
            "created={0}".format(preference.created_at),
            "scope={0}".format(preference.scope),
        ]
        header.extend(self._provenance_bits(preference))
        return [
            "<!-- preference {0} -->".format(" ".join(header)),
            "{0} = {1}".format(preference.key, _json(preference.value)),
            "<!-- /preference -->",
            "",
        ]

    def _render_project_state(self, state):
        # type: (Any) -> List[str]
        header = [
            "id={0}".format(state.id),
            "project={0}".format(state.project_id),
            "created={0}".format(state.created_at),
            "scope={0}".format(state.scope),
        ]
        header.extend(self._provenance_bits(state))
        return [
            "<!-- project-state {0} -->".format(" ".join(header)),
            _json(state.state),
            "<!-- /project-state -->",
            "",
        ]

    # -- pruning -------------------------------------------------------

    def _prune(self, target, written_names):
        # type: (str, set) -> List[str]
        """Delete our own stale files. Never touches anything we did not write."""
        pruned = []
        try:
            entries = sorted(os.listdir(target))
        except OSError:
            return pruned
        for name in entries:
            if not name.lower().endswith(".md"):
                continue
            if name.lower() in written_names or name.lower() == README_NAME.lower():
                continue
            path = os.path.join(target, name)
            if not os.path.isfile(path):
                continue
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as handle:
                    head = handle.read(400)
            except OSError:
                continue
            if GENERATOR_MARKER in head:
                try:
                    os.remove(path)
                    pruned.append(path)
                except OSError:
                    continue
        return pruned


__all__ = ["ObsidianExporter", "ExportReport", "scope_slug", "README_NAME", "GENERATOR_MARKER"]
